export const SUPER_ADMIN_EMAIL = 'lexcorp0777@gmail.com';

export const WHATSAPP_NUMBER = '+1234567890';
export const PHONE_NUMBER = '+1234567890';
export const BUSINESS_EMAIL = 'info@luxdrape.com';
export const BUSINESS_ADDRESS = 'Main Road, Begusarai, Bihar 851101, India';
export const BUSINESS_NAME = 'LuxDrape';
export const BUSINESS_TAGLINE = 'Premium Luxury Curtains & Window Treatments';
export const BUSINESS_CITY = 'Begusarai';
export const BUSINESS_STATE = 'Bihar';
export const BUSINESS_COUNTRY = 'India';
export const BASE_URL = 'https://lumiree.vercel.app';

export const CATEGORIES = [
  { id: 'blackout', name: 'Blackout Curtains', description: 'Complete light blocking for perfect sleep' },
  { id: 'sheer', name: 'Sheer Curtains', description: 'Elegant light-filtering fabrics' },
  { id: 'luxury', name: 'Luxury Curtains', description: 'Premium fabrics for distinguished spaces' },
  { id: 'bedroom', name: 'Bedroom Curtains', description: 'Cozy and stylish bedroom window treatments' },
  { id: 'living-room', name: 'Living Room Curtains', description: 'Statement pieces for your living space' },
  { id: 'office', name: 'Office Curtains', description: 'Professional window solutions' },
  { id: 'hotel', name: 'Hotel Curtains', description: 'Hospitality-grade window treatments' },
  { id: 'modern', name: 'Modern Curtains', description: 'Contemporary designs for modern homes' },
  { id: 'minimal', name: 'Minimal Curtains', description: 'Clean lines and simple elegance' },
  { id: 'printed', name: 'Printed Curtains', description: 'Bold patterns and artistic designs' },
  { id: 'custom', name: 'Custom Curtains', description: 'Tailored to your exact specifications' },
];

export const MATERIALS = [
  'Velvet', 'Silk', 'Linen', 'Cotton', 'Polyester', 'Satin', 'Organza',
  'Jacquard', 'Chenille', 'Damask', 'Faux Silk', 'Blackout Fabric', 'Voile'
];

export const COLORS = [
  { name: 'White', hex: '#FFFFFF' },
  { name: 'Ivory', hex: '#FFFFF0' },
  { name: 'Cream', hex: '#FFFDD0' },
  { name: 'Beige', hex: '#F5F5DC' },
  { name: 'Gold', hex: '#FFD700' },
  { name: 'Champagne', hex: '#F7E7CE' },
  { name: 'Silver', hex: '#C0C0C0' },
  { name: 'Gray', hex: '#808080' },
  { name: 'Charcoal', hex: '#36454F' },
  { name: 'Navy', hex: '#000080' },
  { name: 'Royal Blue', hex: '#4169E1' },
  { name: 'Burgundy', hex: '#800020' },
  { name: 'Wine Red', hex: '#722F37' },
  { name: 'Forest Green', hex: '#228B22' },
  { name: 'Emerald', hex: '#50C878' },
  { name: 'Blush Pink', hex: '#FFB6C1' },
  { name: 'Dusty Rose', hex: '#DCAE96' },
  { name: 'Chocolate', hex: '#7B3F00' },
  { name: 'Black', hex: '#000000' },
  { name: 'Teal', hex: '#008080' },
];

export const CURTAIN_STYLES = [
  'Pinch Pleat', 'Pencil Pleat', 'Eyelet/Grommet', 'Tab Top', 'Rod Pocket',
  'Goblet Pleat', 'Box Pleat', 'Ripple Fold', 'Inverted Pleat', 'Flat Panel'
];

export const ROD_TYPES = [
  'Standard Rod', 'Decorative Rod', 'Traverse Rod', 'Tension Rod',
  'Ceiling Track', 'Wall Track', 'Motorized Track', 'Double Rod'
];

export const PLEAT_STYLES = [
  'Single Pleat', 'Double Pleat', 'Triple Pleat', 'Pencil Pleat',
  'Goblet Pleat', 'Cartridge Pleat', 'Box Pleat', 'Butterfly Pleat'
];

export const STOCK_IMAGES = {
  hero: 'https://images.pexels.com/photos/33839793/pexels-photo-33839793.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=900&w=1600',
  hero2: 'https://images.pexels.com/photos/6207825/pexels-photo-6207825.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=900&w=1600',
  hero3: 'https://images.pexels.com/photos/12214094/pexels-photo-12214094.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=900&w=1600',
  sheer: 'https://images.pexels.com/photos/763147/pexels-photo-763147.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200',
  bedroom: 'https://images.pexels.com/photos/7533840/pexels-photo-7533840.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200',
  livingRoom: 'https://images.pexels.com/photos/7045831/pexels-photo-7045831.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200',
  blackout: 'https://images.pexels.com/photos/4814070/pexels-photo-4814070.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
  luxury: 'https://images.pexels.com/photos/8092428/pexels-photo-8092428.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200',
  modern: 'https://images.pexels.com/photos/7587750/pexels-photo-7587750.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200',
  elegant: 'https://images.pexels.com/photos/34538281/pexels-photo-34538281.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200',
  velvet: 'https://images.pexels.com/photos/19856114/pexels-photo-19856114.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
  fabric: 'https://images.pexels.com/photos/19856109/pexels-photo-19856109.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
  minimal: 'https://images.pexels.com/photos/7587739/pexels-photo-7587739.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200',
  green: 'https://images.pexels.com/photos/7214333/pexels-photo-7214333.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200',
  gold: 'https://images.pexels.com/photos/15679390/pexels-photo-15679390.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
  dark: 'https://images.pexels.com/photos/14663235/pexels-photo-14663235.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
  hotel: 'https://images.pexels.com/photos/6957097/pexels-photo-6957097.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200',
  office: 'https://images.pexels.com/photos/34574607/pexels-photo-34574607.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200',
  vintage: 'https://images.pexels.com/photos/16045135/pexels-photo-16045135.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
  pink: 'https://images.pexels.com/photos/19856113/pexels-photo-19856113.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
  drapes: 'https://images.pexels.com/photos/12944779/pexels-photo-12944779.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200',
  white: 'https://images.pexels.com/photos/7614617/pexels-photo-7614617.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200',
};

export const SAMPLE_PRODUCTS = [
  {
    id: 'prod-1',
    name: 'Royal Velvet Blackout Curtains',
    slug: 'royal-velvet-blackout',
    shortDescription: 'Luxurious velvet blackout curtains with triple-weave technology for complete light blocking.',
    description: 'Experience unparalleled luxury with our Royal Velvet Blackout Curtains. Crafted from premium triple-weave velvet fabric, these curtains provide 100% light blocking while adding an opulent touch to any room. The heavy drape and rich texture create a sophisticated atmosphere perfect for bedrooms, home theaters, and formal living spaces.',
    price: 12999,
    salePrice: 9999,
    category: 'blackout',
    material: 'Velvet',
    colors: ['Burgundy', 'Navy', 'Charcoal', 'Forest Green'],
    sizes: ['W52×L63"', 'W52×L84"', 'W52×L96"', 'W100×L84"'],
    images: [STOCK_IMAGES.blackout, STOCK_IMAGES.dark, STOCK_IMAGES.gold],
    tags: ['blackout', 'velvet', 'luxury', 'bestseller'],
    inStock: true,
    featured: true,
    bestSeller: true,
    newArrival: false,
    rating: 4.8,
    reviewCount: 124,
    careInstructions: 'Dry clean only. Do not bleach. Iron on low heat.',
    installInfo: 'Fits standard curtain rods. Grommets included for easy installation.',
    fabric: 'Premium triple-weave velvet with thermal insulation backing',
  },
  {
    id: 'prod-2',
    name: 'Ethereal Sheer Voile Curtains',
    slug: 'ethereal-sheer-voile',
    shortDescription: 'Delicate sheer voile curtains that filter light beautifully while maintaining privacy.',
    description: 'Transform your windows with our Ethereal Sheer Voile Curtains. These gossamer-light panels create a dreamy, ethereal atmosphere as sunlight filters through the fine voile fabric. Perfect for layering with heavier drapes or as standalone window treatments in living rooms and dining areas.',
    price: 4999,
    salePrice: null,
    category: 'sheer',
    material: 'Voile',
    colors: ['White', 'Ivory', 'Cream', 'Champagne'],
    sizes: ['W54×L63"', 'W54×L84"', 'W54×L96"', 'W108×L84"'],
    images: [STOCK_IMAGES.sheer, STOCK_IMAGES.white, STOCK_IMAGES.bedroom],
    tags: ['sheer', 'voile', 'light-filtering', 'elegant'],
    inStock: true,
    featured: true,
    bestSeller: false,
    newArrival: true,
    rating: 4.6,
    reviewCount: 89,
    careInstructions: 'Machine washable on gentle cycle. Tumble dry low.',
    installInfo: 'Rod pocket or clip rings. Fits rods up to 1.5" diameter.',
    fabric: 'Fine-weave polyester voile with weighted hem',
  },
  {
    id: 'prod-3',
    name: 'Palazzo Silk Damask Drapes',
    slug: 'palazzo-silk-damask',
    shortDescription: 'Opulent silk damask drapes with intricate woven patterns for distinguished interiors.',
    description: 'Our Palazzo Silk Damask Drapes are the epitome of luxury window treatments. Each panel features an intricate damask pattern woven into genuine silk fabric, creating a play of light and shadow that adds dimension and sophistication to formal rooms. Perfect for living rooms, dining rooms, and master bedrooms.',
    price: 24999,
    salePrice: 19999,
    category: 'luxury',
    material: 'Silk',
    colors: ['Gold', 'Champagne', 'Silver', 'Burgundy'],
    sizes: ['W52×L84"', 'W52×L96"', 'W52×L108"', 'W100×L96"'],
    images: [STOCK_IMAGES.drapes, STOCK_IMAGES.luxury, STOCK_IMAGES.elegant],
    tags: ['luxury', 'silk', 'damask', 'premium', 'featured'],
    inStock: true,
    featured: true,
    bestSeller: true,
    newArrival: false,
    rating: 4.9,
    reviewCount: 67,
    careInstructions: 'Professional dry clean only. Avoid direct sunlight exposure.',
    installInfo: 'Pinch pleat heading. Compatible with traverse rods and decorative rods.',
    fabric: 'Pure silk with jacquard damask weave and cotton lining',
  },
  {
    id: 'prod-4',
    name: 'Serene Linen Curtains',
    slug: 'serene-linen',
    shortDescription: 'Natural linen curtains with a relaxed, organic texture for modern and minimal interiors.',
    description: 'Embrace natural beauty with our Serene Linen Curtains. Woven from premium European flax, these curtains bring the organic elegance of linen to your windows. The natural texture and soft drape create a relaxed yet sophisticated look perfect for modern, farmhouse, and coastal interiors.',
    price: 8999,
    salePrice: null,
    category: 'modern',
    material: 'Linen',
    colors: ['White', 'Beige', 'Gray', 'Dusty Rose'],
    sizes: ['W52×L63"', 'W52×L84"', 'W52×L96"'],
    images: [STOCK_IMAGES.modern, STOCK_IMAGES.minimal, STOCK_IMAGES.green],
    tags: ['modern', 'linen', 'natural', 'minimal', 'new'],
    inStock: true,
    featured: false,
    bestSeller: false,
    newArrival: true,
    rating: 4.7,
    reviewCount: 156,
    careInstructions: 'Machine washable cold. Hang dry for best results.',
    installInfo: 'Tab top or clip rings. Casual drape styling.',
    fabric: '100% European flax linen, pre-washed for softness',
  },
  {
    id: 'prod-5',
    name: 'Grand Hotel Pinch Pleat Curtains',
    slug: 'grand-hotel-pinch-pleat',
    shortDescription: 'Professional-grade pinch pleat curtains designed for luxury hotels and upscale residences.',
    description: 'Bring hotel luxury to your home with our Grand Hotel Pinch Pleat Curtains. These professional-grade curtains feature a classic triple pinch pleat heading and are crafted from the same heavy-weight fabric used in five-star hotels worldwide.',
    price: 15999,
    salePrice: 13999,
    category: 'hotel',
    material: 'Polyester',
    colors: ['Charcoal', 'Navy', 'Ivory', 'Beige'],
    sizes: ['W52×L84"', 'W52×L96"', 'W100×L84"', 'W100×L96"'],
    images: [STOCK_IMAGES.hotel, STOCK_IMAGES.livingRoom, STOCK_IMAGES.office],
    tags: ['hotel', 'pinch-pleat', 'professional', 'bestseller'],
    inStock: true,
    featured: true,
    bestSeller: true,
    newArrival: false,
    rating: 4.8,
    reviewCount: 203,
    careInstructions: 'Dry clean recommended. Spot clean with mild detergent.',
    installInfo: 'Triple pinch pleat. Requires traverse rod or drapery hooks.',
    fabric: 'Heavy-weight polyester blend with blackout lining',
  },
  {
    id: 'prod-6',
    name: 'Aurora Printed Curtains',
    slug: 'aurora-printed',
    shortDescription: 'Vibrant digitally printed curtains featuring artistic botanical and geometric patterns.',
    description: 'Make a bold statement with our Aurora Printed Curtains. Each panel features stunning digital prints in vivid colors that transform your windows into works of art. Choose from botanical, geometric, and abstract patterns to match your personal style.',
    price: 7499,
    salePrice: null,
    category: 'printed',
    material: 'Cotton',
    colors: ['Teal', 'Blush Pink', 'Emerald', 'Gold'],
    sizes: ['W52×L63"', 'W52×L84"', 'W52×L96"'],
    images: [STOCK_IMAGES.green, STOCK_IMAGES.velvet, STOCK_IMAGES.pink],
    tags: ['printed', 'artistic', 'colorful', 'new'],
    inStock: true,
    featured: false,
    bestSeller: false,
    newArrival: true,
    rating: 4.5,
    reviewCount: 78,
    careInstructions: 'Machine washable cold. Colors may fade in direct sunlight.',
    installInfo: 'Grommet top. Fits rods up to 1.5" diameter.',
    fabric: '100% cotton canvas with UV-resistant digital print',
  },
  {
    id: 'prod-7',
    name: 'Twilight Blackout Bedroom Curtains',
    slug: 'twilight-blackout-bedroom',
    shortDescription: 'Specially designed bedroom curtains with thermal insulation and noise reduction properties.',
    description: 'Sleep better with our Twilight Blackout Bedroom Curtains. Engineered specifically for bedrooms, these curtains feature advanced thermal insulation technology that blocks light, reduces noise, and maintains room temperature for the perfect sleeping environment.',
    price: 10499,
    salePrice: 8999,
    category: 'bedroom',
    material: 'Polyester',
    colors: ['Charcoal', 'Navy', 'Burgundy', 'Gray'],
    sizes: ['W42×L63"', 'W52×L84"', 'W52×L96"', 'W72×L84"'],
    images: [STOCK_IMAGES.bedroom, STOCK_IMAGES.blackout, STOCK_IMAGES.minimal],
    tags: ['blackout', 'bedroom', 'thermal', 'noise-reducing'],
    inStock: true,
    featured: false,
    bestSeller: true,
    newArrival: false,
    rating: 4.7,
    reviewCount: 312,
    careInstructions: 'Machine washable. Tumble dry low. Do not bleach.',
    installInfo: 'Back tab or rod pocket. Easy DIY installation.',
    fabric: 'Triple-layer thermal insulation polyester',
  },
  {
    id: 'prod-8',
    name: 'Executive Office Window Panels',
    slug: 'executive-office-panels',
    shortDescription: 'Sleek professional curtain panels designed for corporate offices and home workspaces.',
    description: 'Elevate your workspace with our Executive Office Window Panels. These professionally tailored curtains combine light control with a sophisticated corporate aesthetic, featuring clean lines and premium fabrics suitable for boardrooms, executive offices, and home work environments.',
    price: 11999,
    salePrice: null,
    category: 'office',
    material: 'Polyester',
    colors: ['Gray', 'Charcoal', 'Navy', 'Beige'],
    sizes: ['W52×L84"', 'W52×L96"', 'W100×L84"'],
    images: [STOCK_IMAGES.office, STOCK_IMAGES.modern, STOCK_IMAGES.hotel],
    tags: ['office', 'professional', 'sleek', 'modern'],
    inStock: true,
    featured: false,
    bestSeller: false,
    newArrival: true,
    rating: 4.6,
    reviewCount: 45,
    careInstructions: 'Dry clean recommended. Steam to remove wrinkles.',
    installInfo: 'Ceiling track or standard rod compatible.',
    fabric: 'Commercial-grade polyester with light-filtering weave',
  },
  {
    id: 'prod-9',
    name: 'Minimalist Ripple Fold Curtains',
    slug: 'minimalist-ripple-fold',
    shortDescription: 'Clean-lined ripple fold curtains for a sleek, contemporary minimalist aesthetic.',
    description: 'Perfect for minimalist interiors, our Ripple Fold Curtains create uniform, evenly-spaced waves that glide smoothly along a track. The clean, architectural lines complement modern design while providing excellent light control.',
    price: 13999,
    salePrice: 12499,
    category: 'minimal',
    material: 'Polyester',
    colors: ['White', 'Ivory', 'Gray', 'Black'],
    sizes: ['W52×L84"', 'W52×L96"', 'W100×L84"', 'W100×L96"'],
    images: [STOCK_IMAGES.minimal, STOCK_IMAGES.white, STOCK_IMAGES.office],
    tags: ['minimal', 'ripple-fold', 'modern', 'architectural'],
    inStock: true,
    featured: true,
    bestSeller: false,
    newArrival: false,
    rating: 4.8,
    reviewCount: 91,
    careInstructions: 'Dry clean only for best results.',
    installInfo: 'Requires ceiling track system. Professional installation recommended.',
    fabric: 'Smooth-finish polyester with structured weave',
  },
  {
    id: 'prod-10',
    name: 'Living Room Chenille Drapes',
    slug: 'living-room-chenille',
    shortDescription: 'Sumptuous chenille drapes that add warmth and texture to living room windows.',
    description: 'Create a warm, inviting living space with our Chenille Drapes. The plush chenille fabric provides a tactile richness that photographs beautifully and feels incredible to touch. These substantial drapes frame your windows with elegant fullness.',
    price: 14999,
    salePrice: null,
    category: 'living-room',
    material: 'Chenille',
    colors: ['Cream', 'Gold', 'Dusty Rose', 'Chocolate'],
    sizes: ['W52×L84"', 'W52×L96"', 'W100×L84"', 'W100×L96"'],
    images: [STOCK_IMAGES.livingRoom, STOCK_IMAGES.elegant, STOCK_IMAGES.velvet],
    tags: ['living-room', 'chenille', 'textured', 'warm'],
    inStock: true,
    featured: false,
    bestSeller: true,
    newArrival: false,
    rating: 4.7,
    reviewCount: 178,
    careInstructions: 'Dry clean only. Vacuum regularly with upholstery attachment.',
    installInfo: 'Pinch pleat or eyelet. Heavy-duty rod recommended.',
    fabric: '100% polyester chenille with cotton-blend lining',
  },
  {
    id: 'prod-11',
    name: 'Bespoke Custom Tailored Curtains',
    slug: 'bespoke-custom-tailored',
    shortDescription: 'Fully custom curtains made to your exact specifications with premium fabric selection.',
    description: 'Our Bespoke Custom Tailored Curtains are created to your exact measurements and specifications. Choose from over 200 premium fabrics, specify your preferred heading style, lining, and finishing details. Each curtain is hand-crafted by our expert artisans.',
    price: 24999,
    salePrice: null,
    category: 'custom',
    material: 'Various',
    colors: ['Custom Selection Available'],
    sizes: ['Custom Made to Measure'],
    images: [STOCK_IMAGES.fabric, STOCK_IMAGES.velvet, STOCK_IMAGES.pink],
    tags: ['custom', 'bespoke', 'tailored', 'premium', 'made-to-measure'],
    inStock: true,
    featured: true,
    bestSeller: false,
    newArrival: false,
    rating: 5.0,
    reviewCount: 34,
    careInstructions: 'Care instructions provided based on fabric selection.',
    installInfo: 'Professional measurement and installation available.',
    fabric: 'Choose from 200+ premium fabrics',
  },
  {
    id: 'prod-12',
    name: 'Opulence Jacquard Curtains',
    slug: 'opulence-jacquard',
    shortDescription: 'Rich jacquard woven curtains with elaborate baroque-inspired patterns.',
    description: 'Indulge in the Opulence Jacquard Curtains, featuring elaborate baroque-inspired patterns woven directly into the fabric. These statement curtains bring old-world charm and grandeur to formal dining rooms, libraries, and master suites.',
    price: 18999,
    salePrice: 16499,
    category: 'luxury',
    material: 'Jacquard',
    colors: ['Gold', 'Wine Red', 'Emerald', 'Navy'],
    sizes: ['W52×L84"', 'W52×L96"', 'W52×L108"'],
    images: [STOCK_IMAGES.drapes, STOCK_IMAGES.gold, STOCK_IMAGES.vintage],
    tags: ['luxury', 'jacquard', 'baroque', 'formal'],
    inStock: true,
    featured: true,
    bestSeller: false,
    newArrival: true,
    rating: 4.9,
    reviewCount: 56,
    careInstructions: 'Professional dry clean only.',
    installInfo: 'Goblet pleat heading. Decorative rod recommended.',
    fabric: 'Premium jacquard weave with satin-finish reverse',
  },
];

export const SAMPLE_TESTIMONIALS = [
  {
    id: 't1',
    name: 'Sarah Mitchell',
    role: 'Homeowner',
    text: 'The Royal Velvet curtains transformed our bedroom into a luxury retreat. The quality is outstanding and the blackout feature is perfect. We sleep so much better now!',
    rating: 5,
    image: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=150',
    featured: true,
  },
  {
    id: 't2',
    name: 'James Anderson',
    role: 'Interior Designer',
    text: 'As a designer, I recommend LuxDrape to all my clients. The fabric quality, stitching, and finishing are impeccable. Their custom service is truly bespoke.',
    rating: 5,
    image: 'https://images.pexels.com/photos/1043471/pexels-photo-1043471.jpeg?auto=compress&cs=tinysrgb&w=150',
    featured: true,
  },
  {
    id: 't3',
    name: 'Emily Chen',
    role: 'Hotel Manager',
    text: 'We outfitted our entire boutique hotel with LuxDrape curtains. The professional quality and elegant designs impress our guests every day. Outstanding service!',
    rating: 5,
    image: 'https://images.pexels.com/photos/1181690/pexels-photo-1181690.jpeg?auto=compress&cs=tinysrgb&w=150',
    featured: true,
  },
  {
    id: 't4',
    name: 'Michael Roberts',
    role: 'Architect',
    text: 'The minimalist ripple fold curtains are perfect for our modern builds. Clean lines, excellent quality, and the team understood our architectural vision perfectly.',
    rating: 5,
    image: 'https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=150',
    featured: false,
  },
];

export const SAMPLE_FAQS = [
  {
    id: 'f1',
    question: 'What types of curtains do you offer?',
    answer: 'We offer a comprehensive range including Blackout, Sheer, Velvet, Silk, Linen, Jacquard, and Custom curtains. Our collection spans bedroom, living room, office, hotel, modern, minimal, and printed styles.',
    category: 'products',
  },
  {
    id: 'f2',
    question: 'Do you offer custom-made curtains?',
    answer: 'Yes! Our bespoke curtain service allows you to choose from over 200 premium fabrics, specify exact measurements, select heading styles, linings, and finishing details. Each curtain is hand-crafted by our expert artisans.',
    category: 'custom',
  },
  {
    id: 'f3',
    question: 'How do I measure my windows for curtains?',
    answer: 'Measure the width of your window from edge to edge and add 10-20 cm on each side for proper coverage. For length, measure from the rod to where you want the curtains to fall (sill, below sill, or floor). We recommend professional measurement for custom orders.',
    category: 'measuring',
  },
  {
    id: 'f4',
    question: 'Do you provide installation services?',
    answer: 'Yes, we offer professional curtain installation services. Our experienced team handles everything from rod installation to final curtain hanging and styling. Book an installation appointment through our website or contact us directly.',
    category: 'installation',
  },
  {
    id: 'f5',
    question: 'What is your return policy?',
    answer: 'We offer a 7-day satisfaction guarantee on all standard products. Custom-made curtains are non-refundable but we ensure quality through approval of fabric swatches and detailed specifications before production.',
    category: 'policies',
  },
  {
    id: 'f6',
    question: 'Do you offer bulk discounts for hotels and businesses?',
    answer: 'Absolutely! We offer special pricing for bulk orders including hotels, offices, and commercial spaces. Contact our bulk order team through WhatsApp or the contact form for a personalized quote.',
    category: 'pricing',
  },
  {
    id: 'f7',
    question: 'How long does delivery take?',
    answer: 'Standard curtains ship within 3-5 business days. Custom-made curtains take 2-4 weeks depending on complexity. Express shipping is available for standard products.',
    category: 'delivery',
  },
  {
    id: 'f8',
    question: 'How do I care for my curtains?',
    answer: 'Care varies by fabric. Velvet and silk curtains should be dry cleaned. Cotton and polyester curtains can often be machine washed on gentle. We include specific care instructions with every order.',
    category: 'care',
  },
];
